# Generated by Django 5.1.6 on 2026-02-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_seed_popular_top10_each_category'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='catalog_pro_slug_2b1eb6_idx',
            old_name='catalog_pro_slug_3b0c44_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='catalog_pro_is_publ_a48762_idx',
            old_name='catalog_pro_is_publ_6a2b0f_idx',
        ),
        migrations.AddField(
            model_name='product',
            name='documentation_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Документация'),
        ),
        migrations.AddField(
            model_name='product',
            name='extended_description',
            field=models.TextField(blank=True, verbose_name='Расширенное описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='support_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Поддержка (ссылка)'),
        ),
    ]
