# Generated by Django 4.2.30 on 2026-04-24 18:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_add_extended_description_and_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название (для себя)')),
                ('internal_note', models.TextField(blank=True, verbose_name='Внутренняя заметка')),
                ('token', models.CharField(db_index=True, editable=False, max_length=64, unique=True, verbose_name='Секретный токен в ссылке')),
                ('is_active', models.BooleanField(default=True, verbose_name='Приём материалов открыт')),
                ('max_submissions', models.PositiveSmallIntegerField(default=10, help_text='После лимита форма перестанет принимать новые заявки.', verbose_name='Макс. число отправок по ссылке')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Заказ контента (ссылка для биржи)',
                'verbose_name_plural': 'Заказы контента (ссылки для биржи)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_code', models.CharField(db_index=True, editable=False, max_length=24, unique=True, verbose_name='Код для отчёта на бирже')),
                ('body', models.TextField(verbose_name='Текст материала')),
                ('executor_comment', models.CharField(blank=True, max_length=500, verbose_name='Комментарий исполнителя')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='content_submissions/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'txt', 'zip', 'md'])], verbose_name='Файл (необязательно)')),
                ('status', models.CharField(choices=[('pending', 'На премодерации'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], db_index=True, default='pending', max_length=16, verbose_name='Статус модерации')),
                ('moderator_note', models.TextField(blank=True, verbose_name='Заметка модератора')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Отправлено')),
                ('ip_address', models.CharField(blank=True, max_length=45, verbose_name='IP')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='catalog.contentorder', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Заявка с материалом',
                'verbose_name_plural': 'Заявки с материалами (премодерация)',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
