# Generated by Django 4.2.30 on 2026-04-24 18:29

import django.core.validators
from django.db import migrations, models


def forwards_copy_body_to_product_data(apps, schema_editor):
    ContentSubmission = apps.get_model("catalog", "ContentSubmission")
    Category = apps.get_model("catalog", "Category")
    first_cat = Category.objects.order_by("pk").first()
    fk = first_cat.pk if first_cat else None
    for s in ContentSubmission.objects.all():
        body = (getattr(s, "body", None) or "").strip()
        if body:
            pd = {
                "name": "Импорт (старая форма)",
                "short_description": (body[:297] + "…") if len(body) > 300 else body,
                "description": body,
            }
            if fk is not None:
                pd["category_id"] = fk
            s.product_data = pd
        else:
            pd: dict = {"name": "Черновик", "short_description": "—"}
            if fk is not None:
                pd["category_id"] = fk
            s.product_data = pd
        s.save(update_fields=["product_data"])


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_content_orders_and_submissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentsubmission",
            name="product_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Структура совпадает с полями модели Product (без рейтинга, SEO-источника и публикации).",
                verbose_name="Данные карточки (поля как у сервиса)",
            ),
        ),
        migrations.AddField(
            model_name="contentsubmission",
            name="submitted_logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="content_submissions/logos/%Y/%m/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["png", "jpg", "jpeg", "webp", "gif"]
                    )
                ],
                verbose_name="Логотип сервиса",
            ),
        ),
        migrations.AlterField(
            model_name="contentsubmission",
            name="attachment",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="content_submissions/%Y/%m/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "docx", "txt", "zip", "md"]
                    )
                ],
                verbose_name="Доп. файл (необязательно)",
            ),
        ),
        migrations.RunPython(forwards_copy_body_to_product_data, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="contentsubmission",
            name="body",
        ),
    ]
