# Generated by Django 4.2.30 on 2026-04-24 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_submission_product_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentsubmission',
            name='created_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.product', verbose_name='Созданный сервис в каталоге'),
        ),
    ]
